name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore CalisthenicsStore.sln

      - name: Build
        run: dotnet build CalisthenicsStore.sln -c Release --no-restore
        
      - name: Test
        run: dotnet test CalisthenicsStore.sln -c Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: '**/TestResults/*.trx'
